### ISSUE TITLE
Composer Installation?

### ISSUE THREAD

**Issue by duffner** [Nofraud/nofraud_connect#1]
Team, 

Will you make this available via composer through packagist or similar?  Alternatively, if you sent the correct composer definition in the project it could be made available via VCS 

Something like this at a minimum: 

composer config repositories.connect vcs git@github.com:Nofraud/nofraud_connect.git
composer require nofraud/connect

This way composer can treat the GitHub repo as if it's the master tag.  

Thoughts. 

p.s. You have an incorrect URL in your readme git@bitbucket.org:razoyo/mage2-module-nofraud.git which I'm guessing is incorrect.

**Comment by jperalta1989** [comment]
installation through composer has been corrected. Closing out this issue.
