### ISSUE TITLE
Deprecated Functionality: Optional parameter $params declared before required parameter $responseCode is implicitly treated as a required parameter in nofraud/connect/Logger/Logger.php on line 39

### ISSUE THREAD

**Issue by gauravharshranosys** [Nofraud/nofraud_connect#14]
Php version : 8.1
magento version 2.4.4

when running : 
php bin/magento setup:di:compile

then getting below error : 
`Deprecated Functionality: Optional parameter $params declared before required parameter $responseCode is implicitly treated as a required parameter in vendor/nofraud/connect/Logger/Logger.php on line 39`

**Comment by samumaretiya** [comment]
Hi @gauravharshranosys , We are working on this and update you ASAP.

**Comment by samumaretiya** [comment]
Hi @gauravharshranosys , Thanks for reaching out. It seems like you're using our old version of the addon. 

The error is self-explanatory in that the optional function arguments should be in the last.  You can either make the following edits in your setup or you should update your current version to the latest one. 

So, the function signature becomes as

`public function logApiError($apiUrl, $curlError, $responseCode,$params = null)`

Let me know if you have still any query.

Thanks, sam
